Force to use display as translated snippet for global widget in preview
OnTheGoSystems/wpml-page-builders-elementor pull request #42
Opened 2018-09-21 18:02 UTC by strategio

The preview is rendered in the admin so the display as translated snippet is not added to the query by default.

In parallel, we also need to set the CPT `elementor_library` to be displayed as translated (will do this in the remote config files).

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5793

2018-09-24 07:19 UTC, andreasciamanna requested changes

2018-09-24 07:19 UTC, andreasciamanna commented on src/class-wpml-elementor-adjust-global-widget-id.php
> +				'wpml_should_use_display_as_translated_snippet',
@strategio please use the same name as the function (+ prefix): `use_display_as_translated_snippet`.

However, what's "snippet"? The `use_display_as_translated_snippet` callback must contain this information in the PHPDoc. It must tell where this `$display_as_translated` is coming from. A developer should be able to track where the filter is called and I can't find this.

2018-09-24 13:34 UTC, strategio commented on src/class-wpml-elementor-adjust-global-widget-id.php
> +				'wpml_should_use_display_as_translated_snippet',
@andreasciamanna, the filter `wpml_should_use_display_as_translated_snippet` already exists. So I renamed the callback to `should_use_display_as_translated_snippet`.

Also added a comment about the "snippet".

2018-09-24 14:34 UTC, andreasciamanna submitted a review, later dismissed

2018-09-26 02:54 UTC, brucepearson submitted a review, later dismissed
@strategio This looks good. +1

2018-10-02 17:10 UTC, merged