Fix maintenance template query
OnTheGoSystems/wpml-page-builders-elementor pull request #54
Opened 2018-12-10 13:06 UTC by adrianosferreira

This fix is needed because WPML is calling `wp_reset_query` in `\SitePress::get_ls_languages` which happens after Elementor adjusted the query for displaying the coming soon template.

The `wp_reset_query` basically restores the global `wp_the_query`. So, we must adjust it before WPML calls the function.

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5239

2018-12-10 13:16 UTC, adrianosferreira commented
@OnTheGoSystems/wpml please review.

2018-12-10 13:33 UTC, strategio requested changes

2018-12-10 13:33 UTC, strategio commented on src/class-wpml-pb-fix-maintenance-query.php
> +		add_action( 'template_redirect', array( $this, 'fix_global_query' ), 12 );
@adrianosferreira, could you put the `12` in a constant with a meaningful name?

2018-12-10 13:50 UTC, adrianosferreira commented
@strategio done.

2018-12-10 14:05 UTC, strategio submitted a review, later dismissed
+1 @adrianosferreira

2018-12-11 04:01 UTC, brucepearson submitted a review, later dismissed
@adrianosferreira +1

2018-12-11 14:25 UTC, merged